### ISSUE TITLE
Some replays not showing

### ISSUE THREAD

**Issue by JimmyDreambeard** [cpennington/dicedornot#12]
Hi, this replay does not appear to work. The error code shown is below
[Coach-184255-edf27ad6ec1fcc9f63099693d353b526_2021-01-22_23_47_51.zip](https://github.com/cpennington/dicedornot/files/5976467/Coach-184255-edf27ad6ec1fcc9f63099693d353b526_2021-01-22_23_47_51.zip)

TypeError: t.Data.Name.replace is not a function
TypeError: t.Data.Name.replace is not a function
    at new Qa (https://dicedornot.vengefulpickle.com/build/bundle.js:13:158635)
    at https://dicedornot.vengefulpickle.com/build/bundle.js:13:159035
    at Array.map (<anonymous>)
    at new eo (https://dicedornot.vengefulpickle.com/build/bundle.js:13:159027)
    at https://dicedornot.vengefulpickle.com/build/bundle.js:13:159482
    at Array.map (<anonymous>)
    at Function.argsFromXml (https://dicedornot.vengefulpickle.com/build/bundle.js:13:159474)
    at Function.argsFromXml (https://dicedornot.vengefulpickle.com/build/bundle.js:13:160333)
    at Function.argsFromXml (https://dicedornot.vengefulpickle.com/build/bundle.js:13:176992)
    at Function.fromBoardActionResult (https://dicedornot.vengefulpickle.com/build/bundle.js:13:164489)

**Comment by cpennington** [comment]
Fixed! Turns out, it couldn't handle player names that were numbers.
