### ISSUE TITLE
Move actions are not working

### ISSUE THREAD

**Issue by sjogrenm** [cpennington/dicedornot#50]
It looks like Move actions in the replay files don't have an explicit <ActionType>0</ActionType> which causes this on the first move action:
```Error: Unhandled Action Type
    at assertExhaustive (http://localhost:8080/dist/viewer/Viewer.svelte.js:1667:8)
    at dispatchAction (http://localhost:8080/dist/viewer/Viewer.svelte.js:1971:5)
    at http://localhost:8080/dist/viewer/Viewer.svelte.js:2029:11
    at Generator.next (<anonymous>)
    at http://localhost:8080/dist/viewer/Viewer.svelte.js:1736:67
    at new Promise (<anonymous>)
    at __awaiter (http://localhost:8080/dist/viewer/Viewer.svelte.js:1713:10)
    at handleBoardAction (http://localhost:8080/dist/viewer/Viewer.svelte.js:2027:10)
    at http://localhost:8080/dist/viewer/Viewer.svelte.js:2059:12
    at Generator.next (<anonymous>)```

Maybe related to converting to ts and the undefined action type got treated as a 0 in js?

**Comment by cpennington** [comment]
Should be fixed now. Astute analysis of the source of the problem.
