### ISSUE TITLE
Failing to load some replays

### ISSUE THREAD

**Issue by sjogrenm** [cpennington/dicedornot#52]
When loading eg https://dicedornot.vengefulpickle.com/?rebbl=10008814b2 I'm getting this error:
```
TypeError: Cannot read property 'x' of undefined
    at Xt (https://dicedornot.vengefulpickle.com/dist/main.js:11:22355)
    at Function.argsFromXml (https://dicedornot.vengefulpickle.com/dist/main.js:11:54544)
    at Function.fromBoardActionResult (https://dicedornot.vengefulpickle.com/dist/main.js:11:27721)
    at Function.fromAction (https://dicedornot.vengefulpickle.com/dist/main.js:11:27071)
    at https://dicedornot.vengefulpickle.com/dist/main.js:11:26924
    at Array.flatMap (<anonymous>)
    at Function.fromReplayStep (https://dicedornot.vengefulpickle.com/dist/main.js:11:26895)
    at kw (https://dicedornot.vengefulpickle.com/dist/main.js:11:69163)
    at https://dicedornot.vengefulpickle.com/dist/main.js:12:4633
    at Generator.next (<anonymous>)
```

**Comment by sjogrenm** [comment]
Works fine now 👍
